{% set name = "census-parquet" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/census-parquet-{{ version }}.tar.gz
  sha256: ab4c7867ef23a223a01454c459bdccb1334f50b4f492f3b50386dab307113843

build:
  entry_points:
    - run_census_parquet=census_parquet.cli:start
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - dask-geopandas
    - distributed
    - fiona
    - openpyxl
    - pyarrow
    - python >=3.8
    - unzip
    - wget

test:
  imports:
    - census_parquet
  commands:
    - pip check
    - run_census_parquet --help
  requires:
    - pip

about:
  home: https://github.com/makepath/census-parquet
  summary: Tools for generating Parquet files from US Census 2020
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - drstewart19
